// src/app/layout.tsx (修改后)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 简化根布局
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 应用字体的 className 应该移到实际渲染 <body> 的地方，
  // 也就是 src/app/[lang]/layout.tsx
  // 但为了简单起见，我们先让它只返回 children
  return <>{children}</>;
}
